### ISSUE TITLE
Have not found a suitable qt framework AssertionError

### ISSUE THREAD

**Issue by mrsheepmasterdy** [douglaslab/cadnano2#33]
I´m getting this error when I try to run cadnano2. Tried reinstalling pyqt6 but it did not fix this issue. Not sure if it is related or not.

**Comment by sdouglas** [comment]
Please provide the terminal output so we can help diagnose the issue.

**Comment by mrsheepmasterdy** [comment]
Traceback (most recent call last):
  File "C:\Users\andre\anaconda3\Scripts\cadnano2-script.py", line 33, in <module>
    sys.exit(load_entry_point('cadnano2==2.4.8', 'console_scripts', 'cadnano2')())
  File "C:\Users\andre\anaconda3\Scripts\cadnano2-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\andre\anaconda3\lib\importlib\metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "C:\Users\andre\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\andre\anaconda3\lib\site-packages\cadnano2-2.4.8-py3.9.egg\cadnano2\main.py", line 18, in <module>
    cadnano.initAppWithGui()
  File "C:\Users\andre\anaconda3\lib\site-packages\cadnano2-2.4.8-py3.9.egg\cadnano2\cadnano.py", line 43, in initAppWithGui
    from .cadnanoqt import CadnanoQt
  File "C:\Users\andre\anaconda3\lib\site-packages\cadnano2-2.4.8-py3.9.egg\cadnano2\cadnanoqt.py", line 8, in <module>
    util.qtWrapImport('QtWidgets', globals(), ['QApplication'])
  File "C:\Users\andre\anaconda3\lib\site-packages\cadnano2-2.4.8-py3.9.egg\cadnano2\util.py", line 104, in qtWrapImport
    assert(False)  # Have not found a suitable qt framework
AssertionError

**Comment by sdouglas** [comment]
We do not currently support anaconda. Can you try using a non-anaconda venv installation following the [installation instructions](https://github.com/douglaslab/cadnano2#installation)?
