### ISSUE TITLE
Issue in running cadnano2

### ISSUE THREAD

**Issue by Basilico99** [douglaslab/cadnano2#46]
Hello, I am getting a trouble running cadnano2. I have installed it referring README, using a virtual environment on WSL.

cadnano2 : version 2.4.10
PyQt6 : version 6.5.1
sip : version 6.7.9

(cn24x) user@PC:~$ cadnano2
Traceback (most recent call last):
  File "/home/user/.local/bin/cadnano2", line 5, in <module>
    from cadnano2.main import main
  File "/home/user/.local/lib/python3.10/site-packages/cadnano2/main.py", line 18, in <module>
    cadnano.initAppWithGui()
  File "/home/user/.local/lib/python3.10/site-packages/cadnano2/cadnano.py", line 43, in initAppWithGui
    from .cadnanoqt import CadnanoQt
  File "/home/user/.local/lib/python3.10/site-packages/cadnano2/cadnanoqt.py", line 8, in <module>
    util.qtWrapImport('QtWidgets', globals(), ['QApplication'])
  File "/home/user/.local/lib/python3.10/site-packages/cadnano2/util.py", line 104, in qtWrapImport
    assert(False)  # Have not found a suitable qt framework
AssertionError

**Comment by sdouglas** [comment]
Hmm. Can you try creating a few separate virtual environments to test a few things?

First, I see there’s a new version of PyQt6, that may address this issue. Just try a fresh install following the readme and you should get version 6.5.2. 

If that doesn’t help, use another venv and then before installing cadnano2, force install an older version of PyQt6. For example:

`pip install PyQt6==6.5.0`

or even earlier 

`pip install PyQt6==6.4.2`

then pip install cadnano and see if it runs.
