### ISSUE TITLE
Problem with relative imports

### ISSUE THREAD

**Issue by tom-L2534** [douglaslab/cadnano2#48]
On following the installation instructions, the following is the first output on running main.py: 

Traceback (most recent call last):
  File "C:\Users\XXXXX\Documents\GitHub\cadnano2\cadnano2\main.py", line 18, in <module>
    cadnano.initAppWithGui()
  File "C:\Users\XXXXX\Documents\GitHub\cadnano2\cadnano2\.\cadnano.py", line 43, in initAppWithGui
    from .cadnanoqt import CadnanoQt
ImportError: attempted relative import with no known parent package

These relative imports don't seem to work properly, I changed them to just "import X" but progressively making these changes works only until the following:

C:\Users\XXXXX\Documents\GitHub\cadnano2\cadnano2>python main.py
Traceback (most recent call last):
  File "C:\Users\XXXXX\Documents\GitHub\cadnano2\cadnano2\main.py", line 18, in <module>
    cadnano.initAppWithGui()
  File "C:\Users\XXXXX\Documents\GitHub\cadnano2\cadnano2\.\cadnano.py", line 43, in initAppWithGui
    from cadnanoqt import CadnanoQt
  File "C:\Users\XXXXX\Documents\GitHub\cadnano2\cadnano2\.\cadnanoqt.py", line 8, in <module>
    util.qtWrapImport('QtWidgets', globals(), ['QApplication'])
  File "C:\Users\XXXXX\Documents\GitHub\cadnano2\cadnano2\.\util.py", line 101, in qtWrapImport
    return qtWrapImport(name, globaldict, fromlist)
  File "C:\Users\XXXXX\Documents\GitHub\cadnano2\cadnano2\.\util.py", line 109, in qtWrapImportFromDummy
    imports = __import__(modName, globaldict, locals(), fromlist, 0)
ModuleNotFoundError: No module named 'dummyqt.QtWidgets'

Python version is 3.10.7, PyQt is 6.5.2, OS is Windows 11 Enterprise.

**Comment by sdouglas** [comment]
The command to launch cadnano2 has changed, it is no longer via main.py. I recommend reviewing the readme for the latest instructions for how to install in a venv and run.
